<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="5" hostname="DESKTOP-DJ4FDME" failures="1" tests="1" name="Test(failed)" time="0.172" errors="0" timestamp="2024-10-11T07:01:24 IST">
  <testcase classname="demoTestNG.TestScenario" name="first_testcase" time="0.061">
    <failure type="java.lang.AssertionError" message="expected [Hello World] but found [Hello]">
      <![CDATA[java.lang.AssertionError: expected [Hello World] but found [Hello]
at demoTestNG.TestScenario.first_testcase(TestScenario.java:14)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- first_testcase -->
  <testcase classname="demoTestNG.TestScenario" name="sixth_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- sixth_testcase -->
  <testcase classname="demoTestNG.TestScenario" name="third_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- third_testcase -->
  <testcase classname="demoTestNG.TestScenario" name="second_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- second_testcase -->
  <testcase classname="demoTestNG.TestScenario" name="forth_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- forth_testcase -->
  <testcase classname="demoTestNG.TestScenario" name="fifth_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- fifth_testcase -->
</testsuite> <!-- Test(failed) -->
